### ISSUE TITLE
Prototype naar HTML

### ISSUE THREAD

**Issue by vsheo** [vsheo/the-client-website#1]
site map:
![site_map](https://github.com/user-attachments/assets/bbec1a9e-0278-4fa2-846f-ca05af9cc454)

Wireframe + breakdown schets:
![wireframe](https://github.com/user-attachments/assets/2191dcb7-5703-4da1-a12d-b4ffa7321996)

HiFi ontwerpin figma:
https://www.figma.com/design/LI7PmohhjM9KrKI5mfhdJ2/Triple--mediahuis?node-id=0-1&t=ojDitl3EEVQDopzQ-1

**Comment by julia-stevens** [comment]
De HTML validator heeft één error: 
https://validator.w3.org/nu/?doc=https%3A%2F%2Fvsheo.github.io%2Fthe-client-website%2F

<img width="800" alt="image" src="https://github.com/user-attachments/assets/a175915d-89f8-4f16-a216-452d3c9499b0">

https://github.com/vsheo/the-client-website/blob/24286198538adcd453a5614af7c2034720cb87fa/index.html#L63
Je gebruikt hier nu een `section`, maar die moet een h-element hebben. Dus die kun je nog toevoegen, of een ander HTML element gebruiken, zoals `div`

**Comment by ambersr** [comment]
Misschien kan je kijken of je de afbeelding onder de tekst kan bij cards ivm een logischer structuur.
https://github.com/vsheo/the-client-website/blob/24286198538adcd453a5614af7c2034720cb87fa/index.html#L64-L73

Verder ziet de structuur er logisch uit!

**Comment by julia-stevens** [comment]
https://github.com/vsheo/the-client-website/blob/24286198538adcd453a5614af7c2034720cb87fa/index.html#L11-L32
* In dit eerste stuk heb je `header, nav, header` - Misschien kun je hier één `nav` van maken en één `header`

https://github.com/vsheo/the-client-website/blob/24286198538adcd453a5614af7c2034720cb87fa/index.html#L106-L113
* Je gebruikt onderaan nu een `nav`, maar het is misschien netter om hier een `footer` van te maken. Het is dan niet nodig om de links te groeperen met nav, zie de link en kijk bij 'usage notes': https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav

https://github.com/vsheo/the-client-website/blob/24286198538adcd453a5614af7c2034720cb87fa/index.html#L66
* Je gebruikt als eerst een `h3` heading, maar je kunt eigenlijk geen heading levels skippen, zie 'usage notes': https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements

https://github.com/vsheo/the-client-website/blob/24286198538adcd453a5614af7c2034720cb87fa/index.html#L72
* Het lijkt erop dat hier een `>` te veel staat

**Comment by ambersr** [comment]
1. We hebben naar je Figma bestand gekeken. Voor zover we zien ontbreken er geen onderdelen.
2. Wel zien we dat je een ontwerp hebt gemaakt voor voor mobiel en desktop, kijk of je ook een design kan maken voor tablet.
3. In de code zien we het stuk 'Live en stations' niet terugkomen maar dit staat wel in het ontwerp. Probeer hier nog eens naar te kijken. Verder een mooi uitgebreid ontwerp en leuk dat je een eigen ontwerp hebt gemaakt, ziet er goed uit!
4. De viewport is niet echt van toepassing aangezien de belangrijkste content al in het ontwerp weergegeven is.
5. Je hebt op desktop hiërarchie goed toegepast door gebruik te maken van verschillende tekstgroottes en kleurgebruik bij buttons. Op mobiel kan je misschien nog kijken naar de dagen, deze zijn in verhouding wat groot in vergelijking met de kaartjes. Leuk dat je uit jezelf een nieuw ontwerp hebt gemaakt, ziet er al super goed uit!
