### ISSUE TITLE
Semantische HTML

### ISSUE THREAD

**Issue by Naddybs** [vsheo/the-client-website#2]
https://github.com/vsheo/the-client-website/blob/24286198538adcd453a5614af7c2034720cb87fa/index.html#L63-L73

### `Wat is hier het probleem?`

In je voorbeeld heb je een `section` met meerdere `article` elementen, wat prima is, maar er ontbreekt een `heading` voor de hele sectie. Dit maakt het voor zowel de gebruiker als zoekmachines minder duidelijk waar deze sectie over gaat.

Elke `section` zou een eigen `heading` moet hebben, omdat een` section` bedoeld is om voor een specifiek deel van je pagina. Een `heading` maakt duidelijk waar de sectie over gaat, zowel voor mensen die je website gebruiken als voor zoekmachines en schermlezers.

### `Wat kun je beter doen?`

- Voeg een duidelijke heading toe aan de `section`
Door een heading toe te voegen, maak je de structuur van de pagina semantisch sterker en geef je meer context aan de inhoud van de sectie. In dit geval zou een logische heading iets zijn als “Programma’s” of “Radio shows”, omdat je verschillende programma’s presenteert.

[Uitleg over headings & sections](https://web.dev/learn/html/headings-and-sections)

**Comment by vsheo** [comment]
elke section heeft een heading
