### ISSUE TITLE
Maak een eenvoudigere header structuur

### ISSUE THREAD

**Issue by joostf** [vsheo/the-client-website#6]
https://github.com/vsheo/the-client-website/blob/25aec0c1b795399cbade0794c68799d16b468bab/index.html#L11-L32

Hier kan je één header element gebruiken met daarin de verschillende onderdelen; logo, nav, datums, etc.

Hiermee wordt je HTML eenvoudiger en daarmee beter te begrijpen door screen readers en google, én is het makkelijker te stylen met CSS.

De rest van de HTML (voor wat er nu is) ziet er goed gestructureerd uit 🚀

**Comment by vsheo** [comment]
De nav en de list met datums zijn nu in de header.

**Comment by joostf** [comment]
Ziet er goed uit zo 🚀

Jij maakt voor de navigatie van het hoofdmenu gebruik van een _ol_ element. Een iteressante keuze. Waarom kies je daarvoor?

**Comment by vsheo** [comment]
Ik dacht dat ik een ol kon gebruiken omdat de dagen van de week een vaste volgorde heeft

**Comment by joostf** [comment]
Yes, voor de lijst met dagen van de week begreep ik het, alleen de `ol.top_header` kan ik niet helemaal plaatsen..

**Comment by vsheo** [comment]
Ik had een ol gebruikt omdat ik de eerste li links wou hebben en de tweede rechts.
Ik dacht daarom dat de volgende belangrijk was.
Maar ik zou hetzelfde kunnen doen met een ul
